### ISSUE TITLE
Allow `vars_` and `func_` in code actions to be configured

### ISSUE THREAD

**Issue by karthiknadig** [pappasam/jedi-language-server#106]
Currently code action provides random function and variable names when extracting. We want to use set it a constant value like `new_var`, or `new_func`, and let the users change the name as needed.

/cc @luabud

**Comment by pappasam** [comment]
I don't believe this was possible in LSP `3.15`, but it might be possible in LSP `3.16` with [codeAction/resolve](https://microsoft.github.io/language-server-protocol/specification#codeAction_resolve). That said, once again, the same 2 issues:

1. My client (coc) doesn't yet support `3.16`, so this will be hard for me to test in practice until the relevant PR is resolved
2. (bigger issue) pygls doesn't yet support `3.16`

I'm happy to keep this issue, and any other `3.16`-related issues open. We can flag them with a `LSP-3.16` label or something to stay organized

**Comment by pappasam** [comment]
I'd be happy to consider any suggestions you may have here. I've considered this in the past, but specifying data for codeAction is not very straightforward. For example, inline variable doesn't need a new name, but extract into variable does. Additionally, because the LSP spec crams all code actions into LSP request / response, differences between code actions become really hard to handle without editor-specific logic

**Comment by dimbleby** [comment]
https://github.com/microsoft/language-server-protocol/issues/764, and https://github.com/microsoft/language-server-protocol/issues/1164

So far as I can see the TLDR is that the protocol just doesn't support this yet, not even at 3.16.

(`codeAction/resolve` seems like it would be a good opportunity to provide a new name, having chosen the refactoring, but I don't think that's what it's currently is for)

**Comment by karthiknadig** [comment]
@pappasam I was thinking of using `initializationOptions` for this. We wanted to use a constant value in this case instead of the randomly generated names.
