### ISSUE TITLE
Completions unexpectedly add parentheses

### ISSUE THREAD

**Issue by PeterJCLaw** [pappasam/jedi-language-server#124]
Copied from https://github.com/microsoft/vscode-python/issues/15858.

## Environment data

-   VS Code version: 1.55.0
-   Extension version (available under the Extensions sidebar): 2021.3.680753044
-   OS and version: Ubuntu 20.04 LTS
-   Python version: 3.7, deadsnakes
-   Type of virtual environment used: virtualenv
-   Value of the `python.languageServer` setting: JediLSP

## Expected behaviour

``` python
class Thing: pass

Th<tab> # should complete to:
Thing|     # cursor after completed word
```

## Actual behaviour

``` python
class Thing: pass

Th<tab> # should complete to:
Thing(|)  # cursor between completed parens
```

As far as I can tell this is specific to the JediLSP integration -- changing my language server to Jedi results in the expected completion.

It looks like this may also vary by Python version -- in another codebase I'm working on (in a Python 3.5 virtualenv) I don't get this behaviour.

I can maybe see why this is maybe useful if you're planning to construct an instance or calling a function, though there are many other places where callable symbols are used in which you don't want this to happen -- passing them as callbacks and type annotations for example.

**Comment by pappasam** [comment]
@PeterJCLaw thanks for filing this issue! You've stumbled across something I'm aware of, but have found no clear way to resolve within jedi-language-server itself; my personal strategy for dealing with this is to map snippet expansion to a keybinding and call it manually when i want it. I'm a coc.nvim user, so I'm not sure how to recommend this for vscode. If you have any ideas, I'll happily consider them.

This behavior actually comes from snippet expansion: it appears that (at least in your environment) vscode automatically expands snippets when a completion item is selected. In general, snippets expand callables as long as they're outside of the import context (I've special cased that context because you pretty much never want to expand callables at them time they are imported).

Unfortunately, in pretty much any other context, jedi-language-server the language server has no way of knowing whether you want to expand a callable or not. As you've mentioned, there are plenty of situations where you'll pass a callable as a value without calling, or assigned a callable to a variable without calling it. In these situations, it doesn't make sense to expand the snippet. Only the programmer knows whether the programmer should expand a snippet.

**Solution/workaround:** configure your editor to manually expand snippets with a keybinding instead of automatically expanding them on completion.

I'd love to get any thoughts from you on better ways we can handle this from the language server's perspective. I'm trying not to guess too much at what the programmer wants beyond the decisions already made by jedi; that said, I can't control whether an editor automatically expands snippets that aren't intended for automatic expansion...

*I believe the behavior you've observed happens with jedi-language-server for Python 3.6.1+; Python <= 3.6.0 are not currently supported by the language server, so the different behavior you observe is probably not using jedi-language-server.*

**Comment by PeterJCLaw** [comment]
Thanks for the reply.
What's a "snippet" in this context?

I've encountered snippets as a thing in editors that appear in the completions list and expand as placeholders for non-trivial expressions (for example try/except/finally) with placeholders and the like -- those do expand when selected and that's a behaviour that I do still want. I'm guessing that that's something different though?

Or are you saying that the completions offered by jedi-language-server are in fact snippets? (presumably dynamically generated ones) If that's the case, perhaps that's the issue -- that these should be completions rather than full snippets?

I know a bit about Jedi and a bit about the VSCode Python extension, though I've not looked in detail at the actual language server protocol before. Is completions being snippets a limitation of LSP? That would seem rather surprising to me if so.

**Comment by pappasam** [comment]
Snippets are an LSP completion option: <https://microsoft.github.io/language-server-protocol/specification#textDocument_completion>

```typescript
/**
 * Defines whether the insert text in a completion item should be interpreted as
 * plain text or a snippet.
 */
export namespace InsertTextFormat {
	/**
	 * The primary text to be inserted is treated as a plain string.
	 */
	export const PlainText = 1;

	/**
	 * The primary text to be inserted is treated as a snippet.
	 *
	 * A snippet can define tab stops and placeholders with `$1`, `$2`
	 * and `${3:foo}`. `$0` defines the final tab stop, it defaults to
	 * the end of the snippet. Placeholders with equal identifiers are linked,
	 * that is typing in one will update others too.
	 */
	export const Snippet = 2;
}
```

That said, a long time ago, I figured we'd run into cases like this where editors expanded snippets automatically, so I've provided the option to disable snippets: <https://github.com/pappasam/coc-jedi#jedicompletiondisablesnippets>

### jedi.completion.disableSnippets

If your language client supports `CompletionItem` snippets but you don't like them, disable them by setting this option to `true`.

- type: `boolean`
- default: `false`

I'm not sure how these configuration options are configured in vscode-python. @karthiknadig any guidance here for @PeterJCLaw would be much appreciated! I can then add a link to any vscode-python configuration documentation to the README.

**Comment by pappasam** [comment]
In case you're interested in tweaking anything, here's where snippet logic is implemented in this codebase: <https://github.com/pappasam/jedi-language-server/blob/main/jedi_language_server/jedi_utils.py#L284>

**Comment by PeterJCLaw** [comment]
Thanks. Now I can see what it's doing it makes sense (and seems to work ok), I just don't want it to do that.

Given the defaults in other VSCode Python completion engines (and the other support that you get with the signature in VSCode) I suspect that VSCode should probably have this off by default, though I don't feel strongly about what the library default is.

I've had a look and I can't immediately see a setting for this in VSCode. I don't suppose there's a config file somewhere I can put this in which jedi-language-server would pick up as a workaround?

@karthiknadig unless I'm missing a setting here, I suggest we re-open https://github.com/microsoft/vscode-python/issues/15858 and continue the discussion there?

**Comment by pappasam** [comment]
@PeterJCLaw since this is now being tracked elsewhere, I'm going to close this issue here. Please let me know if you disagree!

**Comment by yujinyuz** [comment]
For those coming from neovim and wanted to disable this feature, just add these settings into your config

```lua
require('lspconfig').jedi_language_server.setup {
  init_options = {
    completion = {
        disableSnippets = true
    }
  }
}
```

**Comment by alex-a-pereira** [comment]
@yujinyuz thank you, that's exactly what I needed. For anyone else reading this - here's a visual on what `disableSnippets = true` does:

When `disableSnippets = false`, classes are shown with a `~` and will complete with parents when the completion is accepted (enter, tab, or whatever you have set)
![image](https://github.com/pappasam/jedi-language-server/assets/36137079/5f363ea8-f8b0-48ae-9428-959612c49871)


After setting `disableSnippets = true`, classes are shown without the `~` and when the completion accepted, it doesn't fill the parens.

![image](https://github.com/pappasam/jedi-language-server/assets/36137079/441ab55a-f7c1-47f8-b822-34deda38de6c)
