### ISSUE TITLE
Tooltip docstring rendering

### ISSUE THREAD

**Issue by karthiknadig** [pappasam/jedi-language-server#172]
Filed by @flaviut

When I view docstrings in tooltips, they look like this, and suck to read:

![tooltip with the text all run together](https://user-images.githubusercontent.com/5213469/140244699-b5e73b38-53d6-49b9-bfdc-8cec31eea685.png)

It'd be really nice if the tooltips were reasonably formatted, like this:

![tooltip example with good formatting](https://user-images.githubusercontent.com/5213469/140244980-ba92e937-49ed-40dc-9a50-29871d610e45.png)

**Comment by pappasam** [comment]
@karthiknadig Here is what I observe from this user's complaints:

1. Newlines within the parameter list aren't nicely displayed in vscode
2. The "tooltip" removes some text (eg, type information)
3. The "tooltip" reformats some of the restructured text, but not all of it (see `:py:meth:` text within "clean"
4. Some information is re-ordered (eg, path to the name is put at the top, not the bottom)

What specific feature, other than general "betterness", is this user requesting? And what do you think makes sense for us to focus on? The Hover text is something we've been focusing on for a while and have made a lot of progress on; I'm sure we can always do better here, but I'm having a hard time figuring out what to start / ignore / defer / pay attention to here.

**Comment by karthiknadig** [comment]
@flaviut Any inputs on this?

**Comment by flaviut** [comment]
We could get 95% of the way there if [rST field lists were supported](https://docutils.sourceforge.io/docs/user/rst/quickref.html#field-lists).

Basically, the plugin ought to have a heuristic that asks "are we looking at a rST docstring? A Google docstring? A NumPy docstring?" and passes it off to the correct plugin.

For the particular points:

1. isn't particularly important since it just comes from incorrectly parsing rST
2. I don't see this at all in this case, but I didn't dig further
3. Not quite. Whatever rST parser you're using isn't following the spec for roles, which says:
   >[ A role marker consists of a colon, the role name, and another colon. A role name is a single word consisting of alphanumerics plus isolated internal hyphens, underscores, plus signs, colons, and periods; no whitespace or other characters are allowed.](https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#toc-entry-49)
4. personal preference really, it doesn't really matter to me

**Comment by krassowski** [comment]
> Basically, the plugin ought to have a heuristic that asks "are we looking at a rST docstring? A Google docstring? A NumPy docstring?" and passes it off to the correct parser.

Yes, that's the idea of https://github.com/python-lsp/docstring-to-markdown - PRs welcome.

> Not quite. Whatever rST parser you're using isn't following the spec for roles, which says:

On the level of roles there is no proper parsing, just substitution of things which are likely to occur in the docstrings. It was well tested on numpy, pandas and friends but the library you mention seems to be using plain Sphinx for docstrings; different role names should be formatted differently so we cannot just have a single catch-all rule as you may envision. Indeed many Sphinx rules were not implemented (as those did not occur in docstrings of packages I was testing against), but I am adding those in https://github.com/python-lsp/docstring-to-markdown/pull/13 - you are welcome to review this PR :)

**Comment by krassowski** [comment]
v0.10 is now on PyPI - curiously waiting to see how it works out; if it's not enough we can iterate further.

**Comment by pappasam** [comment]
@krassowski this is already looking a heck of a lot better! One area of potential improvement might be the handling of newlines within paragraphs and lists. Eg, Python docstrings contain hard-wrapped lines; we might consider putting in some logic that elegantly handles newlines from your RST->markdown converted formatting so that line breaks don't appear to be randomly inserted. Screenshot of what now see in Neovim:

![image](https://user-images.githubusercontent.com/3723671/142281866-a6e58e1e-4f80-4368-8cbd-fee33d93a5f9.png)

**Comment by pappasam** [comment]
Alright, given the lack of response and the fact that I think the changes made by @krassowski are a marked improvement, I'm going to consider this particular issue closed. Please file a new issue if any other issues are discovered involving docstring rendering!
