### ISSUE TITLE
 Implement smart select

### ISSUE THREAD

**Issue by Grawp** [pappasam/jedi-language-server#192]
This is a humble feature request: Implement https://code.visualstudio.com/api/references/vscode-api#SelectionRangeProvider .
Such functionality has been present in Intellij products like PyCharm for many years but is (arguably) sorely missing VSCode/ium.

Proprietary Pylance recently got this functionality https://github.com/microsoft/pylance-release/issues/266
It would be nice if Jedi got it too.

**Comment by Grawp** [comment]
Relevant issue in vscode-python: https://github.com/microsoft/vscode-python/issues/6669

**Comment by Grawp** [comment]
Even better. I can point you to an official VSCode documentation with such gif: https://code.visualstudio.com/docs/editor/codebasics#_shrinkexpand-selection :)

**Comment by dimbleby** [comment]
This looks to be much the same as the "incremental selection" that neovim offers through tree sitter - https://github.com/nvim-treesitter/nvim-treesitter/tree/6e7c8c4fede3dba3845f6a31d98746646b9831dc#incremental-selection.  So that's an alternative approach, at least for neovim users.

I'm not sure whether this would be considered in scope for this project:

- From a language server point of view I guess this is <https://microsoft.github.io/language-server-protocol/specification#textDocument_selectionRange>?  
- But this is the _jedi_  language server, and I don't see that jedi offers anything like this.

Anyway I guess that a likely necessary first step to getting support here would be to add support in jedi: you could try raising a feature request over there, but my guess would be that unless you're able to offer a working MR it's unlikely to get much traction.

**Comment by pappasam** [comment]
Per @dimbleby 's comment, closing as out of scope. We can re-open if Jedi gets support for this.
