### ISSUE TITLE
[FeatureRequest] `F2` rename import typing, should result changes in function annotations

### ISSUE THREAD

**Issue by loynoir** [pappasam/jedi-language-server#194]
### Actual
Change type from `pre` to `post`

Pre:
```python
if typing.TYPE_CHECKING:
    from custom_types import pre

def parse_args() -> 'pre':
    return foobar
```

Post:

Error: `Name "pre" is not defined`
```python
if typing.TYPE_CHECKING:
    from custom_types import post

def parse_args() -> 'pre':
    return foobar
```

### Expected
Change type from `pre` to `post`

Pre:
```python
if typing.TYPE_CHECKING:
    from custom_types import pre

def parse_args() -> 'pre':
    return foobar
```

Post:
```python
if typing.TYPE_CHECKING:
    from custom_types import post

def parse_args() -> 'post':
    return foobar
```

**Comment by loynoir** [comment]
https://github.com/microsoft/vscode-python/issues/18366

**Comment by pappasam** [comment]
@loynoir this appears to be an issue where string annotations are not recognized by Jedi. If you remove the quotes around `pre`, things should work as expected.

Since all this logic is handled by Jedi, we should consider this a Jedi issue and file this issue upstream here: https://github.com/davidhalter/jedi
