### ISSUE TITLE
Can't get workspace symbols

### ISSUE THREAD

**Issue by geekingfrog** [pappasam/jedi-language-server#41]
I am using `jedi-language-server` version `0.19.3` with  [languageClient-neovim](https://github.com/autozimu/LanguageClient-neovim) and I can't get `workspace_symbols` to work. When I invoke it, I get the error `invalid type: null, expected sequence`.

I'm not sure how to get more info about this error.
I have the same setup for rust with rust-analyzer and it works, so it has something to do with jedi-language-client.

**Comment by pappasam** [comment]
This looks like a bug in languageClient-neovim. It should expect a `null` response for workspace symbols that aren't found.

`result: SymbolInformation[] | null as defined above.`

https://microsoft.github.io/language-server-protocol/specification#workspace_symbol

That said, I'm still not happy with Jedi's support for workspace symbols. `Project.search` isn't performing very well for me with `coc.nvim` at present, so I'll keep this issue open as a reminder that I need to look further into this.

**Comment by pappasam** [comment]
I've released a new version that better-handles workspacesymbols!

Although I'm not certain, I suspect languageClient-neovim can be found here: https://github.com/autozimu/LanguageClient-neovim/blob/0e5c9546bfddbaa2b01e5056389c25aefc8bf989/src/language_server_protocol.rs#L1909

Please check with that repo and let me know! If there is a bug with this language server, I'd like to fix it. Otherwise, I look forward to being able to close this issue.

**Comment by geekingfrog** [comment]
oh woa !
I was quite busy and couldn't dig more, but it's now fixed with version `0.19.4`. I have now the workspace symbols feature working, thanks.
