### ISSUE TITLE
Use OptionalVersionedTextDocumentIdentifier in TextDocumentEdit

### ISSUE THREAD

**Issue by karthiknadig** [pappasam/jedi-language-server#61]
From the spec:
https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocumentEdit

This should be OptionalVersionedTextDocumentIdentifier:
https://github.com/pappasam/jedi-language-server/blob/2c6224d07d5f9bc31bf0fc256cdd15e982759425/jedi_language_server/text_edit_utils.py#L73

Using `version=None` currently breaks CodeActions in VS Code. Workaround is to use `version=0` there instead.

**Comment by pappasam** [comment]
Ah, the spec changed:

- https://microsoft.github.io/language-server-protocol/specifications/specification-3-15/#versionedTextDocumentIdentifier
- https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/#versionedTextDocumentIdentifier

I'll follow your workaround because supporting `OptionalVersionedTextDocumentIdentifier` might not be backwards compatible with previous LSP versions.
